### ISSUE TITLE
Extend `.mcpd.toml` schema to capture 'required' variables

### ISSUE THREAD

**Issue by peteski22** [mozilla-ai/mcpd#38]
### Is your feature request related to a problem? Please describe.

When starting the `daemon` and parsing the project and execution context configuration files, we don't currently capture which variables (env vars/cmd line args) are required to start the MCP server.

If we knew this, then we could pre-emptively issue warnings and not just try to start an MCP server that won't run correctly.

### Schema update

Extend the `.mcpd.toml` schema to store **required** vars.

### Example

If we pretend that mcp-server-time requires the `local-timezone` arg, and make up another example..  

```toml
[[servers]]
  name = "time"
  package = "uvx::mcp-server-time@0.6.2"
  tools = ["get_current_time", "convert_time"]

  [[servers.requires]]
    type = "arg"
    name = "--local-timezone"
    description = "The local timezone, e.g., Europe/London" # When available.

[[servers]]
  name = "foobar"
  package = "uvx::mcp-server-foobar@4.5.6"
  tools = ["get_foo"]

  [[servers.requires]]
    type = "env"
    name = "FOO_API_KEY"
    description = "The API key for the foo data provider"

  [[servers.requires]]
    type = "env"
    name = "BAR_API_SECRET"
    description = "The API secret for the bar data provider"

  [[servers.requires]]
    type = "arg"
    name = "--thing"
    description = "The 'thing' value used to determine something or other"
```

### Usage

* `mcpd daemon` could then validate the presence of variables and handle missing values appropriately
* `mcpd` could use this to offer an interactive prompt to configure required values (stored in `~/.secrets.dev.toml`)

### Additional Context

* **Breaking change** to the structure of the `.mcpd.toml` file! 

### Self-Checklist

- [x] I have read the [Contributing Guidelines](CONTRIBUTING.md).
- [x] I have searched the existing issues and found no duplicate.
- [x] I have provided a clear and concise description of the problem.
- [x] I have provided a clear and concise description of the proposed solution.
