### ISSUE TITLE
Command: Align behaviour between adding env vars and adding args

### ISSUE THREAD

**Issue by peteski22** [mozilla-ai/mcpd#44]
Current behaviour between the commands isn't consistent:

* `mcpd config set-args` replaces **all** arguments for an MCP server as long as there is at least one arg specified in the command
* `mcpd config set-env` replaces (or adds) only the env var specified in the command

### Example: set-env 

Running:

```bash
mcpd config set-env time --env foo=bar --env qwerty=123
```

Produces the following in `~/.mcpd/secrets.dev.toml`:

```toml
[servers]
  [servers.time]
    [servers.time.env]
      foo = "bar"
      qwerty = "123"
```

Then running:

```bash
mcpd config set-env time --env foo=baz
```

Updates only the specified env var (as you'd expect):

```toml
[servers]
  [servers.time]
    [servers.time.env]
      foo = "baz"
      qwerty = "123"
```

### Example: set-args

Running:

```bash
mcpd config set-args time --arg --myarg1=foo --arg myarg2=bar
```

Produces the following in `~/.mcpd/secrets.dev.toml`:

```toml
[servers]
  [servers.time]
    args = ["--myarg1=foo", "myarg2=bar"]
```

Then running:

```bash
mcpd config set-args time --arg --myarg1=baz
```

Replaces all the args with the only the ones specified in this command execution:

```toml
[servers]
  [servers.time]
    args = ["--myarg1=baz"]
```

### Describe the solution you'd like

* Update the `mcpd config set-args` command to behave in the same way that `mcpd config set-env` does
  * Allow updating or removing individual arguments
  * Don't clear other args if they weren't re-specified

### Self-Checklist

- [x] I have read the [Contributing Guidelines](CONTRIBUTING.md).
- [x] I have searched the existing issues and found no duplicate.
- [x] I have provided a clear and concise description of the problem.
- [x] I have provided a clear and concise description of the proposed solution.
