### ISSUE TITLE
Command: add `mcpd config export`

### ISSUE THREAD

**Issue by peteski22** [mozilla-ai/mcpd#48]
Following the initial PoC design doc which describes `mcpd config export-env`, we need to add support for exporting a project's configuration so that it can easily and securely be set it up in a CI/CD pipeline or production environment (without manually tracking every required variable).

```bash
mcpd config export
```

### New command: 

```bash
mcpd config export
```

Summary: Bridges the gap between local development and automated environments like CI/CD or production.

Using a project's required configuration from `.mcpd.toml` and the locally configured runtime values from the execution context file (`~/.config/mcpd/secrets.dev.toml`), generates a pair of safe and portable configuration files:

* **Environment Contract**: 
  * Lists all required and configured environment variables as secure, namespace'd placeholders (e.g., `MCPD__{SERVER_NAME}__{ENV_VAR}`).
  * Creates placeholders for command line arguments to be populated with env vars (e.g., `MCPD__{SERVER_NAME}__ARG_{ARG_NAME}`). 
  * This file is intended for the platform operator or CI/CD system.

* **Portable Execution Context**: 
  * A new `secrets.toml` file that defines the runtime args and env sections for each server, using the placeholders from the environment contract. 

Both of these files are **safe to check into version control**.

This allows running an `mcpd` project in **any** environment, cleanly separating the configuration structure from the secret values.

### Flags

* `--format` (string, optional) - the format of the exported environment output (`dotenv` (default), `kubernetes-secret`, `github-actions`)

* `--contract-output` (string, optional) - output path for the templated environment file

* `--context-output` (string, optional) - output path for the templated execution context config file

Global flags:

* `--config-file` - the path to the `.mcpd.toml` file (defaults to working directory)

* `--runtime-file` - the path to the execution context configuration file (defaults to `~/.config/mcpd/secrets.dev.toml`

### Supported `--format` values

| Value                           | Generated file | Description.                                                                                                    | 
| --------------------- | --------------- | --------------------------------------------------------------------- | 
| `dotenv`                     | `.env`                |  The default. For local use, Docker, and many CI systems.                     |
| `kubernetes-secret` |  `secret.yaml`   | A Kubernetes `Secret` manifest for cloud-native deployments             | 
| `github-actions`        |  `env.txt`           |  A simple `KEY=VALUE` file for sourcing in GitHub Actions workflows |

#### Config files

Fake `.mcpd.toml`:

```toml
[[servers]]
  name = "github"
  package = "npx::@modelcontextprotocol/server-github@latest"
  tools = ["get_pull_request_status", "get_pull_request_reviews", "push_files" ]
  required_env = ["GITHUB_PERSONAL_ACCESS_TOKEN"]
  required_args = ["--argkey1", "--argkey2"]

[[servers]]
  name = "mcp-discord"
  package = "npx::mcp-discord@1.3.2"
  tools = ["test", "discord_read_messages", "discord_login", "discord_send"]
  required_env = ["DISCORD_TOKEN"]
  required_args = ["--argkey3"]
```

Fake `~/.config/mcpd/secrets.dev.toml`

```toml
[servers]
  [servers.github]
    args = ["--argkey1=xxx", "--argkey2=yyy", "--argkey9=999"]
    [servers.github.env]
      GITHUB_PERSONAL_ACCESS_TOKEN = "qwerty123"
   
  [servers.mcp-discord]
    args = ["--argkey3=zzz"]
    [servers.mcp-discord.env]
      DISCORD_TOKEN = "my-discord-token-foo"

  [servers.time]
    args = ["--local-timezone=Europe/London"]
```

#### Command (dotenv format)

```bash
mcpd config export --format dotenv --contract-output .env.prod --context-output secrets.prod.toml
```

##### Environment Contract

`dotenv`:

```bash
# Server: github
MCPD__GITHUB__GITHUB_PERSONAL_ACCESS_TOKEN=${MCPD__GITHUB__GITHUB_PERSONAL_ACCESS_TOKEN}
MCPD__GITHUB__ARG__ARG_KEY_1=${MCPD__GITHUB__ARG__ARG_KEY_1}
MCPD__GITHUB__ARG__ARG_KEY_2=${MCPD__GITHUB__ARG__ARG_KEY_2}
MCPD__GITHUB__ARG__ARG_KEY_9=${MCPD__GITHUB__ARG__ARG_KEY_9}

# Server: mcp-discord
MCPD__MCP_DISCORD__DISCORD_TOKEN=${MCPD__MCP_DISCORD__DISCORD_TOKEN}
MCPD__MCP_DISCORD__ARG__ARG_KEY_3=${MCPD__MCP_DISCORD__ARG__ARG_KEY_3}
```

`github-actions`

```yaml
# Paste this 'env' block into your GitHub Actions workflow file.
# Ensure corresponding repository secrets are created.
env:
  MCPD__GITHUB__GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.MCPD__GITHUB__GITHUB_PERSONAL_ACCESS_TOKEN}}
  MCPD__GITHUB__ARG__ARG_KEY_1: ${{ secrets.MCPD__GITHUB__ARG__ARG_KEY_1 }}
  MCPD__GITHUB__ARG__ARG_KEY_2: ${{ secrets.MCPD__GITHUB__ARG__ARG_KEY_2 }}
  MCPD__GITHUB__ARG__ARG_KEY_9: ${{ secrets.MCPD__GITHUB__ARG__ARG_KEY_9 }}
  MCPD__MCP_DISCORD__DISCORD_TOKEN: ${{ secrets.MCPD__GITHUB__GITHUB_PERSONAL_ACCESS_TOKEN }}
  MCPD__MCP_DISCORD__ARG__ARG_KEY_3: ${{ secrets.MCPD__MCP_DISCORD__ARG__ARG_KEY_3 }}
```

`kubernetes-secret`

WIP...

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mcpd-project-secrets
type: Opaque
stringData:
  VARIABLE_NAME: ""
```

##### Portable Execution Context

`secrets.prod.toml`:

```toml
# This file was auto-generated by 'mcpd config export'
[servers]
  [servers.github]
    [servers.github.env]
      GITHUB_PERSONAL_ACCESS_TOKEN = "${MCPD__GITHUB__GITHUB_PERSONAL_ACCESS_TOKEN}"
    args = [
      "--argkey1=${MCPD__GITHUB__ARG__ARG_KEY_1}",
      "--argkey2=${MCPD__GITHUB__ARG__ARG_KEY_2}",
      "--argkey9=${MCPD__GITHUB__ARG__ARG_KEY_9}"
    ]

 [servers.mcp-discord]
    [servers.mcp-discord.env]
      DISCORD_TOKEN = "${MCPD__MCP_DISCORD__DISCORD_TOKEN}"
    args = ["--argkey3=${MCPD__MCP_DISCORD__ARG__ARG_KEY_3}"]
```

### Additional Context

* Required updates to documentation to cover how this works and can be used.
* Should also support boolean cmd line arg flags

### Self-Checklist

- [x] I have read the [Contributing Guidelines](CONTRIBUTING.md).
- [x] I have searched the existing issues and found no duplicate.
- [x] I have provided a clear and concise description of the problem.
- [x] I have provided a clear and concise description of the proposed solution.
